import Appbar from "@/components/common/AppBar";
import Head from "next/head";
import { useEffect, useState } from "react";

import { CssBaseline, ThemeProvider } from "@mui/material";
import { lightTheme, darkTheme } from "@/styles/mui/theme";
import { useDispatch, useSelector } from "react-redux";
import { selectTheme } from "@/redux/reducer/themeReducer";

export default function Blog() {
   const dispatch = useDispatch();
  const currentTheme = useSelector(selectTheme).activeTheme;
  // const [currentTheme, setCurrentTheme] = useState("light");

  useEffect(() => {
    dispatch(getActiveTheme()); // To get theme from Cookie
  }, []);

  return (
    <>
      <ThemeProvider theme={currentTheme === "dark" ? darkTheme : lightTheme}>
        <CssBaseline />
        <Head>
          <title>Blog | The Movie Lovers Club</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Appbar />
        <div>Blog Page</div>
      </ThemeProvider>
    </>
  );
}
