import Appbar from "@/components/common/AppBar";
import Head from "next/head";
import { useState } from "react";

import { CssBaseline, ThemeProvider } from "@mui/material";
import { lightTheme, darkTheme } from "@/styles/mui/theme";

export default function Blog() {
  const [currentTheme, setCurrentTheme] = useState("light");

  return (
    <>
      <ThemeProvider theme={currentTheme === "dark" ? darkTheme : lightTheme}>
        <CssBaseline />
        <Head>
          <title>Blog | The Movie Lovers Club</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Appbar setCurrentTheme={setCurrentTheme} currentTheme={currentTheme} />
        <div>Blog Page</div>
      </ThemeProvider>
    </>
  );
}
