import Head from "next/head";
import { useEffect, useState } from "react";
//MUI Imports
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Appbar from "@/components/common/AppBar";
import {
  Container,
  CssBaseline,
  Grid,
  ThemeProvider,
} from "@mui/material";
import { lightTheme, darkTheme } from "@/styles/mui/theme";

//card imports
import { CustomCard } from "../components/common/customComponent";
import { useSelector, useDispatch } from "react-redux";
import { selectTheme, getActiveTheme } from "@/redux/reducer/themeReducer";

export default function Home() {
  // const [currentTheme, setCurrentTheme] = useState("light");
  // const [visible, setVisible] = useState(false);
  const dispatch = useDispatch();
  const currentTheme = useSelector(selectTheme).activeTheme;

  useEffect(() => {
    dispatch(getActiveTheme()); // To get theme from Cookie
  }, []);

  const movies = [
    {
      name: "Avengers",
      img: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/7b350a2f-0b3e-4033-8125-34c4d67e3bbe/compose?aspectRatio=1.78&format=webp&width=1200",
      desc: "Directed by Joss Whedon",
    },
    {
      name: "Terminator",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqsW3jntlwkuRcxsIT1rLpjtC3HuMukv7elQ&s",
      desc: "Directed by james cameron",
    },
    {
      name: "Inceptor",
      img: "https://i.ytimg.com/vi/_Mc0TZueRQE/maxresdefault.jpg",
      desc: "Directed by Chris Nolan",
    },
    {
      name: "Jurassic Park",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMs7X6ePzaoeG2pl3Q8gXOw6blAFrfh4G-VQ&s",
      desc: "Directed by Steven spieling",
    },
  ];
  return (
    <>
      <ThemeProvider theme={currentTheme === "dark" ? darkTheme : lightTheme}>
        <CssBaseline />
        <Head>
          <title>The Movie Lovers Club</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Appbar />
        {/* <Button onClick={() => setVisible(!visible)}>TOGGLE</Button>

        <Box height="200px">
          {visible ? (
            <Box
              sx={{ background: "grey", width: "500px", height: "300px" }}
            ></Box>
          ) : (
            <></>
          )} */}
        <Box margin={"25px"}>
          <Container>
            <Grid container spacing={2} direction="row" justifyContent="center">
              {movies ? (
                movies.map((movie) => (
                  <Grid size={{xl: 4, md: 4, xs: 12}}>
                    <CustomCard
                      name={movie.name}
                      image={movie.img}
                      desc={movie.desc}
                    />
                  </Grid>
                ))
              ) : (
                <></>
              )}
            </Grid>
          </Container>
        </Box>
      </ThemeProvider>
    </>
  );
}
