import Head from "next/head";
import { useState } from "react";
//MUI Imports
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Appbar from "@/components/common/AppBar";
import { CssBaseline, Grid, ThemeProvider, useTheme } from "@mui/material";
import { lightTheme, darkTheme } from "@/styles/mui/theme";

//card imports
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import { MyCard } from "../components/common/customComponent";

export default function Home() {
  const [currentTheme, setCurrentTheme] = useState("light");
  const [visible, setVisible] = useState(false);
  const theme = useTheme();
  const movies = [
    {
      name: "Avengers",
      img: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/7b350a2f-0b3e-4033-8125-34c4d67e3bbe/compose?aspectRatio=1.78&format=webp&width=1200",
      desc: "Directed by Joss Whedon",
    },
    {
      name: "Terminator",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqsW3jntlwkuRcxsIT1rLpjtC3HuMukv7elQ&s",
      desc: "Directed by james cameron",
    },
    {
      name: "Inceptor",
      img: "https://i.ytimg.com/vi/_Mc0TZueRQE/maxresdefault.jpg",
      desc: "Directed by Chris Nolan",
    },
    {
      name: "Jurassic Park",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMs7X6ePzaoeG2pl3Q8gXOw6blAFrfh4G-VQ&s",
      desc: "Directed by Steven spieling",
    },
  ];
  return (
    <>
      <ThemeProvider theme={currentTheme === "dark" ? darkTheme : lightTheme}>
        <CssBaseline />
        <Head>
          <title>The Movie Lovers Club</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Appbar setCurrentTheme={setCurrentTheme} currentTheme={currentTheme} />
        <Button onClick={() => setVisible(!visible)}>TOGGLE</Button>

        <Box height="200px">
          {visible ? (
            <Box
              sx={{ background: "grey", width: "500px", height: "300px" }}
            ></Box>
          ) : (
            <></>
          )}
          <Grid>
<Grid>
          <MyCard>
            <CardMedia
              sx={{ height: 140 }}
              image="https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/7b350a2f-0b3e-4033-8125-34c4d67e3bbe/compose?aspectRatio=1.78&format=webp&width=1200"
              title="green iguana"
            />
            <CardContent>
              <Typography gutterBottom variant="h5" component="div">
                Lizard
              </Typography>
              <Typography variant="body2" sx={{ color: "text.secondary" }}>
                Lizards are a widespread group of squamate reptiles, with over
                6,000 species, ranging across all continents except Antarctica
              </Typography>
            </CardContent>
            <CardActions>
              <Button size="small">Share</Button>
              <Button size="small">Learn More</Button>
            </CardActions>
          </MyCard>
          </Grid>
          </Grid>
        </Box>
      </ThemeProvider>
    </>
  );
}
